In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv("Real_Estate_Data_150.csv") #Load csv file
df

,Bedrooms,Carpet_Area,Total_Price,Per_Sqfoot,Location,Aminities
0,2,796,7164000,9000,Ravet,Kids Play Area
1,3,1045,9405000,9000,Punawale,Pet Park
2,4,1485,13365000,9000,Chinchwad,Sky Infinity Edge Pool
3,3,1266,11394000,9000,Tathawde,Mini Restaurant
4,2,832,7488000,9000,Wakad,Gymnasium
...,...,...,...,...,...,...
145,3,1276,11484000,9000,Moshi,Sky Infinity Edge Pool
146,3,1248,11232000,9000,Tathawde,Mini Restaurant
147,4,1454,13086000,9000,Tathawde,Captivating Spa
148,2,1311,11799000,9000,Ravet,Palm Court
149,2,1342,12078000,9000,Moshi,Private Screening Arena

In [ ]:
from sklearn.preprocessing import LabelEncoder  #Convert categorical labels into numerical integers

le_location=LabelEncoder()
le_aminities=LabelEncoder()

df['location_n']=le_location.fit_transform(df['Location'])
df['aminities_n']=le_aminities.fit_transform(df['Aminities'])
df

,Bedrooms,Carpet_Area,Total_Price,Per_Sqfoot,Location,Aminities,location_n,aminities_n
0,2,796,7164000,9000,Ravet,Kids Play Area,3,2
1,3,1045,9405000,9000,Punawale,Pet Park,2,5
2,4,1485,13365000,9000,Chinchwad,Sky Infinity Edge Pool,0,7
3,3,1266,11394000,9000,Tathawde,Mini Restaurant,4,3
4,2,832,7488000,9000,Wakad,Gymnasium,5,1
...,...,...,...,...,...,...,...,...
145,3,1276,11484000,9000,Moshi,Sky Infinity Edge Pool,1,7
146,3,1248,11232000,9000,Tathawde,Mini Restaurant,4,3
147,4,1454,13086000,9000,Tathawde,Captivating Spa,4,0
148,2,1311,11799000,9000,Ravet,Palm Court,3,4
149,2,1342,12078000,9000,Moshi,Private Screening Arena,1,6

In [ ]:
target=df['Total_Price']
target

0       7164000
1       9405000
2      13365000
3      11394000
4       7488000
         ...
145    11484000
146    11232000
147    13086000
148    11799000
149    12078000
Name: Total_Price, Length: 150, dtype: int64

In [ ]:
df1=df.drop(['Total_Price','Location','Aminities'],axis='columns')
df1

     Bedrooms  Carpet_Area  Per_Sqfoot  location_n  aminities_n
0           2          796        9000           3            2
1           3         1045        9000           2            5
2           4         1485        9000           0            7
3           3         1266        9000           4            3
4           2          832        9000           5            1
..        ...          ...         ...         ...          ...
145         3         1276        9000           1            7
146         3         1248        9000           4            3
147         4         1454        9000           4            0
148         2         1311        9000           3            4
149         2         1342        9000           1            6

[150 rows x 5 columns]

In [ ]:
target

0       7164000
1       9405000
2      13365000
3      11394000
4       7488000
         ...
145    11484000
146    11232000
147    13086000
148    11799000
149    12078000
Name: Total_Price, Length: 150, dtype: int64

In [ ]:
df

,Bedrooms,Carpet_Area,Total_Price,Per_Sqfoot,Location,Aminities,location_n,aminities_n
0,2,796,7164000,9000,Ravet,Kids Play Area,3,2
1,3,1045,9405000,9000,Punawale,Pet Park,2,5
2,4,1485,13365000,9000,Chinchwad,Sky Infinity Edge Pool,0,7
3,3,1266,11394000,9000,Tathawde,Mini Restaurant,4,3
4,2,832,7488000,9000,Wakad,Gymnasium,5,1
...,...,...,...,...,...,...,...,...
145,3,1276,11484000,9000,Moshi,Sky Infinity Edge Pool,1,7
146,3,1248,11232000,9000,Tathawde,Mini Restaurant,4,3
147,4,1454,13086000,9000,Tathawde,Captivating Spa,4,0
148,2,1311,11799000,9000,Ravet,Palm Court,3,4
149,2,1342,12078000,9000,Moshi,Private Screening Arena,1,6

In [ ]:
from tkinter import ttk
import tkinter as tk
from tkinter import messagebox
import numpy as np
from sklearn import linear_model

# ------------------ MODEL ------------------
model = linear_model.LinearRegression()
model.fit(df1,target)

# ------------------ GUI ------------------
root = tk.Tk()
root.title("🏡 SmartProperty AI")
root.geometry("450x600")

# -------- Bedrooms --------
tk.Label(root, text="Select Bedrooms").pack()
bedroom_var = tk.IntVar(value=2)
tk.OptionMenu(root, bedroom_var, 1,2,3,4,5,6).pack()

# -------- Carpet Area (Range Slider) --------
tk.Label(root, text="Carpet Area (700 - 1500)").pack()
carpet_scale = tk.Scale(root, from_=700, to=1500, orient="horizontal")
carpet_scale.set(900)
carpet_scale.pack()

# -------- Price per sqft (Slider) --------
tk.Label(root, text="Price per Sqft (8000 - 10000)").pack()
sqft_scale = tk.Scale(root, from_=8000, to=10000, orient="horizontal")
sqft_scale.set(9000)
sqft_scale.pack()

# -------- Location (Names) --------
tk.Label(root, text="Select Location").pack()

locations = {
    "Chinchwad":0,
    "Moshi":1,
    "Punawale":2,
    "Ravet":3,
    "Tathawade":4,
    "Wakad":5
}

location_var = tk.StringVar()
location_var.set("Chinchwad")

tk.OptionMenu(root, location_var, *locations.keys()).pack()

# -------- Amenities --------
tk.Label(root, text="Select Amenities").pack()

amenities_vars = []
amenities_names = [
    "Spa", "Gym", "Kids Area",
    "Restaurant", "Palm Court", "Pet Park"
]

for name in amenities_names:
    var = tk.IntVar()
    tk.Checkbutton(root, text=name, variable=var).pack(anchor='w')
    amenities_vars.append(var)

# -------- Prediction --------
def predict_price():
    try:
        bedroom = bedroom_var.get()
        carpet_area = carpet_scale.get()
        per_sqft = sqft_scale.get()

        location_name = location_var.get()
        location = locations[location_name]

        amenity_feature = sum(var.get() for var in amenities_vars)

        prediction = model.predict([[bedroom, carpet_area, per_sqft, location, amenity_feature]])

        messagebox.showinfo("Result", f"Estimated Price: ₹ {int(prediction[0])}")

    except:
        messagebox.showerror("Error", "Invalid Input")

# -------- Button --------
tk.Button(root, text="Predict Price", command=predict_price,
          bg="green", fg="white", font=("Arial", 12)).pack(pady=20)

# Run
root.mainloop()